application: remote-creator
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "4d 5h"

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "10d"

- url: .*
  script: main.app

